apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: secret-rolebinding
    namespace: nginx-julian
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: secret-role
subjects:
  - kind: ServiceAccount
    name: aws-load-balancer-controller
    namespace: kube-system