apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: secret-role
    namespace: nginx-julian
rules:
  - apiGroups:
       - ""
    resourceNames:
      - my-k8s-secret
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch